"use client";
import {useEffect,useState} from "react";import Nav from "../components/Nav";
const ROOT="https://hintbcyjdctjyyqtoice.supabase.co";const API=ROOT+"/rest/v1/listings?select=id,source_name,source_sku,current_price,regular_price,promo_price,stock_status,last_checked_at,product_url,sources(name)&order=last_checked_at.desc";const KEY="sb_publishable_klMGC7-avcMFiJyrZ7ypLQ_CUF3pwsi";
export default function Products(){const[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[email,setEmail]=useState("onuma.jamuang@gmail.com"),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
const load=()=>{setLoading(true);fetch(API,{headers:{apikey:KEY}}).then(r=>r.json()).then(d=>setRows(Array.isArray(d)?d:[])).finally(()=>setLoading(false))};
useEffect(()=>{load();const h=location.hash;if(h.includes("access_token=")){const q=new URLSearchParams(h.slice(1));const t=q.get("access_token");if(t){sessionStorage.setItem("admin_access_token",t);history.replaceState(null,"",location.pathname);setMsg("เข้าสู่ระบบผู้ดูแลแล้ว")}}},[]);
const login=async()=>{setBusy(true);setMsg("");try{const redirect=location.origin+"/construction-material-price-monitor/products/";const r=await fetch(ROOT+"/auth/v1/otp?redirect_to="+encodeURIComponent(redirect),{method:"POST",headers:{apikey:KEY,"Content-Type":"application/json"},body:JSON.stringify({email,create_user:true})});if(!r.ok)throw new Error("ส่งลิงก์เข้าสู่ระบบไม่สำเร็จ");setSent(true);setMsg("ส่งลิงก์เข้าสู่ระบบไปที่อีเมลแล้ว")}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
const clearAll=async()=>{const token=sessionStorage.getItem("admin_access_token");if(!token){setMsg("กรุณาเข้าสู่ระบบผู้ดูแลก่อนล้างข้อมูล");return}if(!confirm("ต้องการล้างข้อมูลวัสดุและประวัติราคาทั้งหมดใช่หรือไม่?"))return;if(prompt('พิมพ์คำว่า "ล้างข้อมูลทั้งหมด" เพื่อยืนยัน')!=="ล้างข้อมูลทั้งหมด")return;setBusy(true);setMsg("");try{const r=await fetch(ROOT+"/functions/v1/clear-material-data",{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({confirm:"CLEAR_ALL"})});const d=await r.json();if(!r.ok)throw new Error(d.error||"ล้างข้อมูลไม่สำเร็จ");setMsg("ล้างข้อมูลทั้งหมดเรียบร้อยแล้ว");load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
return <div className="app"><Nav/><main className="content"><header><div><p className="eyebrow">MATERIAL CATALOG</p><h1>รายการวัสดุ</h1><p className="muted">รายการสินค้าที่บันทึกจากทุกแหล่งข้อมูล</p></div></header>
<div className="panel" style={{padding:18,marginBottom:16}}><b>ผู้ดูแลระบบ</b><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:10}}><input value={email} onChange={e=>setEmail(e.target.value)} style={{flex:"1 1 300px",minHeight:42}}/><button onClick={login} disabled={busy} className="primary">{sent?"ส่งลิงก์อีกครั้ง":"เข้าสู่ระบบทางอีเมล"}</button><button onClick={clearAll} disabled={busy||!rows.length} style={{minHeight:42,padding:"0 16px",border:"1px solid #dc2626",color:"#dc2626",background:"#fff",borderRadius:8,cursor:"pointer"}}>ล้างข้อมูลทั้งหมด</button></div>{msg&&<p style={{marginBottom:0}}>{msg}</p>}</div>
<div className="panel tableWrap"><table className="table"><thead><tr><th>สินค้า</th><th>SKU</th><th>แหล่งข้อมูล</th><th>ราคาล่าสุด</th><th>ตรวจสอบล่าสุด</th><th>สถานะ</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><a href={x.product_url} target="_blank" rel="noreferrer">{x.source_name}</a></td><td>{x.source_sku||"—"}</td><td>{x.sources?.name||"—"}</td><td><b>฿{Number(x.current_price||0).toLocaleString("th-TH",{minimumFractionDigits:2})}</b></td><td>{x.last_checked_at?new Date(x.last_checked_at).toLocaleString("th-TH"):"—"}</td><td>{x.stock_status||"ตรวจแล้ว"}</td></tr>)}{!loading&&!rows.length&&<tr><td colSpan={6}><div className="empty"><b>ยังไม่มีรายการสินค้า</b><span>ไปที่เมนูเก็บข้อมูลราคาเพื่อเพิ่มรายการ</span></div></td></tr>}</tbody></table>{loading&&<div className="empty"><span>กำลังโหลดข้อมูล...</span></div>}</div></main></div>}